#!/bin/bash
RUN=$1

#untab
UNT=$(cat $RUN | sed -e "s/[$(printf '\t') ][$(printf '\t') ]*/ /g")

#select first 5 columns
NAM=$(echo "$UNT" | cut -d' ' -f 6- | sort | uniq -c | head -n 1 | awk '{$1=$1;print}' | cut -d' ' -f 2)
SEL=$(echo "$UNT" | cut -d' ' -f 1-5 | sed "s/$/ "$NAM"/")

#remove incomplete rows
CLE=$(echo "$SEL" | awk -F' ' 'NF>=6')

#find duplicates, list(topicId, documentId)
DUP=$(echo "$CLE" | cut -d" " -f 1,3 | awk '{ print $2 " " $1}' | sort | uniq -d | awk '{$1=$1;print}' | awk '{ print $2 " " $1}')

#find index duplicates rows and remove from the polished file
ITD=$(echo "$DUP" | xargs -n 2 bash -c 'grep -n $1 '$RUN' | grep $0 | sed 1d ' | cut -d':' -f 1 | sed "s/$/d;/" | xargs | sed "s/ //g" | sed "s/;$//")

if [ -z "${ITD}" ]; then
	echo "$CLE"
else
    sed -e $ITD $RUN
fi